### ISSUE TITLE
请问这款插件什么时候可以制作完？

### ISSUE THREAD

**Issue by ZherKing** [MrXiaoM/SweetMail#1]
最近在找邮箱插件，翻到您的插件了，就是有点好奇大概什么时候能做好
可以支持1.21吗？
另外 我好像在 [MiraiForum](https://mirai.mamoe.net/) 遇到您 应该是本人吧？

**Comment by MrXiaoM** [comment]
还差一点就完成了，但是最近我在准备考科一还有一堆乱七八糟到事情，暂时没空写。
插件没有用到 NMS，理论应该支持全版本。

**Comment by ZherKing** [comment]
好的好的，期待插件的完成
挺巧的 我也在考驾照
