### ISSUE TITLE
示例看不懂

### ISSUE THREAD

**Issue by windy664** [MrXiaoM/SweetMail#11]
> import top.mrxiaom.sweetmail.IMail;
// 使用示例
void foo() {
    IMail.Status status = IMail.api()
            .createSystemMail("系统消息")
            .setIcon("BOOK") // 设置图标，详见源码注释
            .setTitle("邮件标题")
            .addContent("邮件正文内容", "列表中每个元素代表每页。换行依旧用\n")
            .addAttachments( // 添加附件
                AttachmentItem.build(new ItemStack(Material.DIAMOND))
            )
            .send();
    if (status.ok()) {
        info("邮件发送成功");
    }
}

这里怎么发送一个带有NBT的物品，或者用NBTAPI构建的物品
还有那个注册器怎么注册一个指令类型的呀？

**Comment by MrXiaoM** [comment]
`//添加附近` 注释下面就是添加物品的示例啊… 你会不会写插件的…

还有，“注册器”是什么意思

**Comment by windy664** [comment]
> `//添加附件` 注释下面就是添加物品的示例啊… 你会不会写插件的…
> 
> 还有，“注册器”是什么意思

注册自定义附件类型

**Comment by windy664** [comment]
> `//添加附件` 注释下面就是添加物品的示例啊… 你会不会写插件的…
> 
> 还有，“注册器”是什么意思

怎么发送一个带有nbt的物品，因为我看插件也没有NBTAPI的依赖

**Comment by MrXiaoM** [comment]
> 怎么发送一个带有nbt的物品，因为我看插件也没有NBTAPI的依赖
哪里没有了
```
implementation("de.tr7zw:item-nbt-api:2.14.0")
```
再说了，编辑nbt又不关我插件的事，是你插件的事，我插件又不关心你的物品是怎么来的，传进来就行了啊

**Comment by windy664** [comment]
可以解释下这个示例是怎么发送给指定玩家的吗，我好像没看到player这个参数

**Comment by MrXiaoM** [comment]
`setReceiverFromPlayer(OfflinePlayer)`
`setReceiverFromPlayers(List<OfflinePlayer>)`
