### ISSUE TITLE
【功能增强】关于邮件自动销毁功能

### ISSUE THREAD

**Issue by addpromax** [MrXiaoM/SweetMail#3]
为了防止玩家把邮件系统当仓库用，应该增加此功能，设置一个玩家邮件默认邮件时间，禁止玩家给自己发邮件。如果可以的话 按照权限节点或者权限组来控制销毁时间。

系统邮件也应该有销毁时间 管理员从高级菜单设置

**Comment by MrXiaoM** [comment]
```yaml
# 是否能向自己发送邮件
can-send-to-yourself: false
```
早就有了，默认关的

**Comment by MrXiaoM** [comment]
等我有空写个草稿附件持有时间，超时不发送或拿走，自动移除

**Comment by addpromax** [comment]
不光是草稿 收件箱我觉得也有必要有销毁时间

**Comment by addpromax** [comment]
那就静候了

**Comment by MrXiaoM** [comment]
收件箱的附件有效期写好了
