### ISSUE TITLE
添加一个发送邮件给全服在线离线的玩家

### ISSUE THREAD

**Issue by wlm1455925277** [MrXiaoM/SweetMail#4]
我看到了时间发送但是添加一个我觉得一个会比较方便！

**Comment by MrXiaoM** [comment]
已经有全服在线玩家支持了

**Comment by wlm1455925277** [comment]
> 已经有全服在线玩家支持了

可以支持所有玩家么就是不管离线或者在线玩家都可以收到这对于发送补偿邮件很有用，如果插件在发送邮件时没有经济插件那么就会报错，希望邮件到期可以提上日程

**Comment by wlm1455925277** [comment]
> 发限制总不可能发到全服玩家吧，包括已经不玩的，会产生非常多的数据量，这就是为什么我要写上线时间

所以这样邮件销毁时间就有作用了啊

**Comment by MrXiaoM** [comment]
> 所以这样邮件销毁时间就有作用了啊

销毁是不会销毁数据的，只会让玩家无法领取。垃圾数据该在的依然还会在

**Comment by MrXiaoM** [comment]
这个功能不要想了，前两天我测试泛收件人发现这并不现实。  
我服务器离线玩家账号有一万多个，发送邮件花了十几秒才响应。
