### ISSUE TITLE
【功能增强】增加邮件模板功能 增加物品翻页功能 过多物品的lore自动省略

### ISSUE THREAD

**Issue by addpromax** [MrXiaoM/SweetMail#6]
增加仅供管理员和外部插件API调用的插件模板功能

1.增加模板配置文件，允许配置通用模板
2.增加API以允许第三方插件调用对应模板
3.高级菜单增加模板功能，允许管理员使用模板快速发布邮件

**Comment by addpromax** [comment]
增加物品翻页功能，如果要配合第三方插件的话 有可能会导致物品过多。
增加过多物品的lore自动省略，如果物品过多，lore很长 后面的过多物品应该省略成
`...（以及30项物品）`

**Comment by MrXiaoM** [comment]
78b1a66
