### ISSUE TITLE
【BUG】多个Bug反馈

### ISSUE THREAD

**Issue by addpromax** [MrXiaoM/SweetMail#7]
1.当你使用命令打开/sweetmail inbox打开收件箱时，点击邮件信息后，书本处点击完成，重新使用命令就无法正常打开。除非退出服务器

2.有个第三方插件SakuraBind(https://github.com/SakuraTown/SakuraBind/releases) 使用本插件发送丢失物品，物品超过一定数量时候会导致发送的邮件附件数量不对，作者说是你的问题。
测试方法：
1.装插件
2.绑定一个物品（64个草方块）/bind bind item
3.放到箱子内
4.箱子下面有岩浆
5.打破箱子
6.查看邮件
[SakuraBind-2.3.20.zip](https://github.com/user-attachments/files/16918873/SakuraBind-2.3.20.zip) 这个附件改成jar之后测试。

3.重复领取附件的调试信息没有删除

**Comment by MrXiaoM** [comment]
跟箱子有什么关系

**Comment by addpromax** [comment]
和箱子没关系 就是模拟一下丢失大量物品的时候的反应

**Comment by addpromax** [comment]
数量少没问题。超过一定数量就不正常工作了

**Comment by MrXiaoM** [comment]
具体是怎么数量不对，我目前没空测试

**Comment by addpromax** [comment]
比如丢失了1780个物品 但是只有几百个回来了

**Comment by addpromax** [comment]
调用的时候发的是1780个 插件作者用debug看的

**Comment by addpromax** [comment]
debug:
![1229523a68e26b80abb4174eea1b89f7](https://github.com/user-attachments/assets/055a5c75-e932-447d-b8ef-a14455b7ce2d)
实际情况：
![image](https://github.com/user-attachments/assets/1c3e831a-458e-4bf9-9fe5-1ff09c1afbce)

**Comment by addpromax** [comment]
还有第三方作者反馈：
正版用uuid 离线用玩家名，会导致第三方作者调用的时候非常麻烦
![image](https://github.com/user-attachments/assets/206ebd02-c101-4150-8c9f-5e9f433a65f8)

**Comment by MrXiaoM** [comment]
配置文件不是有 online-mode 开关吗

**Comment by MrXiaoM** [comment]
主要是都用 uuid，离线服多服有可能有uuid不一样的抽象情况，都用玩家名，正版服有玩家可改名的抽象情况
